SG-4610 Fix execution scope (#4)
Fixes a bug, which means that when executing functions that use imports and variables from the global scope, it will no longer error.
Previously executing the following would throw an error:

```
a = "hello"
def say_something():
    print(a)
say_something()

>> NameError: global name 'a' is not defined
```
Huge thanks to @jhultgre for providing this fix.
Co-authored-by: Philip Scadding <pscadding@users.noreply.github.com>